use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::Path,
};

use adr_core::{AdrDocument, AdrId, AdrIndexEntry, LoadedConfig, build_adr_index};

use crate::{
    components::{AdrPageComponent, IndexPageComponent, Render},
    error::{Result, SiteError},
};

const STYLES: &str = include_str!("templates/plain.css");
const THEME_SCRIPT: &str = include_str!("templates/theme.js");
const INTER_FONT: &[u8] = include_bytes!("templates/fonts/Inter-Regular.woff2");
const JETBRAINS_MONO_FONT: &[u8] = include_bytes!("templates/fonts/JetBrainsMono-Regular.woff2");
const SITE_TITLE: &str = "Architectural Decision Records";
const ADR_HOME_LABEL: &str = "← All ADRs";
const SITE_FOOTER: &str = "Generated by <code>adr-site</code>.";

pub fn build_site(config: &LoadedConfig, output_dir: &Path) -> Result<()> {
    if output_dir.exists() {
        fs::remove_dir_all(output_dir).map_err(|source| SiteError::DirectoryRemove {
            path: output_dir.to_path_buf(),
            source,
        })?;
    }

    create_dir(output_dir)?;
    create_dir(&output_dir.join("adr"))?;
    create_dir(&output_dir.join("fonts"))?;
    write_file(&output_dir.join("styles.css"), STYLES)?;
    write_file(&output_dir.join("theme.js"), THEME_SCRIPT)?;
    write_binary_file(&output_dir.join("fonts/Inter-Regular.woff2"), INTER_FONT)?;
    write_binary_file(
        &output_dir.join("fonts/JetBrainsMono-Regular.woff2"),
        JETBRAINS_MONO_FONT,
    )?;

    let index = build_adr_index(config)?;
    let documents = index
        .entries
        .iter()
        .map(|entry| entry.document.clone())
        .collect::<Vec<_>>();
    let documents_by_id = documents
        .iter()
        .map(|document| (document.id, document))
        .collect::<BTreeMap<_, _>>();
    let known_ids = documents
        .iter()
        .map(|document| document.id)
        .collect::<BTreeSet<_>>();

    write_index_page(output_dir, &documents)?;
    for (position, entry) in index.entries.iter().enumerate() {
        let previous = position.checked_sub(1).and_then(|idx| documents.get(idx));
        let next = documents.get(position + 1);
        write_adr_page(
            output_dir,
            entry,
            previous,
            next,
            &documents_by_id,
            &known_ids,
        )?;
    }

    Ok(())
}

fn write_index_page(output_dir: &Path, documents: &[AdrDocument]) -> Result<()> {
    let page = IndexPageComponent {
        documents,
        home_label: SITE_TITLE,
        footer: SITE_FOOTER,
    }
    .render();

    write_file(&output_dir.join("index.html"), &page)
}

fn write_adr_page(
    output_dir: &Path,
    entry: &AdrIndexEntry,
    previous: Option<&AdrDocument>,
    next: Option<&AdrDocument>,
    documents_by_id: &BTreeMap<AdrId, &AdrDocument>,
    known_ids: &BTreeSet<AdrId>,
) -> Result<()> {
    let markdown_body = read_markdown_body(&entry.document.path)?;
    let page = AdrPageComponent {
        entry,
        previous,
        next,
        documents_by_id,
        known_ids,
        markdown_body: &markdown_body,
        home_label: ADR_HOME_LABEL,
        footer: SITE_FOOTER,
    }
    .render();

    let page_dir = output_dir.join("adr").join(entry.document.id.to_string());
    create_dir(&page_dir)?;
    write_file(&page_dir.join("index.html"), &page)
}

fn read_markdown_body(path: &Path) -> Result<String> {
    let content = fs::read_to_string(path).map_err(|source| SiteError::FileRead {
        path: path.to_path_buf(),
        source,
    })?;
    let normalized = content.replace("\r\n", "\n");

    Ok(strip_frontmatter(&normalized)
        .unwrap_or(&normalized)
        .to_string())
}

fn strip_frontmatter(content: &str) -> Option<&str> {
    let rest = content.strip_prefix("---\n")?;
    let end = rest.find("\n---\n")?;
    Some(&rest[end + 5..])
}

fn create_dir(path: &Path) -> Result<()> {
    fs::create_dir_all(path).map_err(|source| SiteError::DirectoryCreate {
        path: path.to_path_buf(),
        source,
    })
}

fn write_file(path: &Path, content: &str) -> Result<()> {
    fs::write(path, content).map_err(|source| SiteError::FileWrite {
        path: path.to_path_buf(),
        source,
    })
}

fn write_binary_file(path: &Path, content: &[u8]) -> Result<()> {
    fs::write(path, content).map_err(|source| SiteError::FileWrite {
        path: path.to_path_buf(),
        source,
    })
}
